remote_theme: pages-themes/minimal@v0.2.0
title: Sol Benkel 🐦🌱
description: Astroparticle Physicist & Computer Engineer from Valparaíso, Chile. Currently based in Berlin, Germany.
plugins:
    - jekyll-remote-theme
